### ISSUE TITLE
Latest commit breaks the bot

### ISSUE THREAD

**Issue by zztopper** [nlef/moonraker-telegram-bot#13]
Just make a git pull and restarted service
```
May 02 19:44:30 voron2 python[20020]: 2021-05-02 19:44:30,000 - apscheduler.scheduler - INFO - Scheduler started
May 02 19:44:48 voron2 python[20020]: 2021-05-02 19:44:48,746 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
May 02 19:44:48 voron2 python[20020]: Traceback (most recent call last):
May 02 19:44:48 voron2 python[20020]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
May 02 19:44:48 voron2 python[20020]:     handler.handle_update(update, self, check, context)
May 02 19:44:48 voron2 python[20020]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.7/site-packages/telegram/ext/handler.py", line 160, in handle_update
May 02 19:44:48 voron2 python[20020]:     return self.callback(update, context)
May 02 19:44:48 voron2 python[20020]:   File "/home/pi/moonraker-telegram-bot/main.py", line 138, in status
May 02 19:44:48 voron2 python[20020]:     message_to_reply.reply_text(get_status())
May 02 19:44:48 voron2 python[20020]:   File "/home/pi/moonraker-telegram-bot/main.py", line 114, in get_status
May 02 19:44:48 voron2 python[20020]:     light_status = get_light_status()
May 02 19:44:48 voron2 python[20020]:   File "/home/pi/moonraker-telegram-bot/main.py", line 128, in get_light_status
May 02 19:44:48 voron2 python[20020]:     response = urllib.request.urlopen(f"http://{host}/machine/device_power/status?{light_device}")
May 02 19:44:48 voron2 python[20020]:   File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
May 02 19:44:48 voron2 python[20020]:     return opener.open(url, data, timeout)
May 02 19:44:48 voron2 python[20020]:   File "/usr/lib/python3.7/urllib/request.py", line 531, in open
May 02 19:44:48 voron2 python[20020]:     response = meth(req, response)
May 02 19:44:48 voron2 python[20020]:   File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
May 02 19:44:48 voron2 python[20020]:     'http', request, response, code, msg, hdrs)
May 02 19:44:48 voron2 python[20020]:   File "/usr/lib/python3.7/urllib/request.py", line 569, in error
May 02 19:44:48 voron2 python[20020]:     return self._call_chain(*args)
May 02 19:44:48 voron2 python[20020]:   File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
May 02 19:44:48 voron2 python[20020]:     result = func(*args)
May 02 19:44:48 voron2 python[20020]:   File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
May 02 19:44:48 voron2 python[20020]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
May 02 19:44:48 voron2 python[20020]: urllib.error.HTTPError: HTTP Error 404: Not Found
May 02 19:46:39 voron2 systemd[1]: Stopping Starts Moonraker Telegram Bot on startup...
```

**Comment by nlef** [comment]
yes, some unchecked code was merged and it's my mistake.
this bug is fixed.
Pls check!
