### ISSUE TITLE
[Bug]: Timelapse won't work and other errors....

### ISSUE THREAD

**Issue by nG64** [nlef/moonraker-telegram-bot#131]
### What happened and in what context?

The bot isn't able to create a timelapse. Status updates are working and i also can request a /video

### If needed, paste the relevant bot log contents here.

2022-04-04 15:56:57,628 - __main__ - ERROR - Job f7ec24eec26940b7898d44bc5fcc6b10 raised[Errno 2] No such file or directory: '/home/pi/timelapse/nutinsert.gcode_2022-04-04_15-46/lapse.lock'
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/timelapse.py", line 266, in _send_lapse
    ) = self._camera.create_timelapse(lapse_filename, gcode_name, info_mess)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 388, in create_timelapse
    return self._create_timelapse(printing_filename, gcode_name, info_mess)
  File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 423, in _create_timelapse
    lock_file.touch()
  File "/usr/lib/python3.9/pathlib.py", line 1304, in touch
    fd = self._raw_open(flags, mode)
  File "/usr/lib/python3.9/pathlib.py", line 1116, in _raw_open
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/timelapse/nutinsert.gcode_2022-04-04_15-46/lapse.lock'

2022-04-04 16:14:43,824 - __main__ - WARNING - klippy disconnect detected with message: notify_klippy_disconnected
2022-04-04 16:36:58,045 - __main__ - ERROR - Job 8abda3284f234d28a5b4a0cf5ea3dcab raisedCanceled by new editmessagemedia request
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 182, in _notify
    self._status_message.edit_media(media=InputMediaPhoto(photo))
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2096, in edit_media
    return self.bot.edit_message_media(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2916, in edit_message_media
    return self._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Canceled by new editmessagemedia request
2022-04-04 16:37:32,999 - __main__ - ERROR - Job notifier_timer raisedCanceled by new editmessagemedia request
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 334, in _notify_by_time
    self._schedule_notification()
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 307, in _schedule_notification
    self._notify(mess, self._silent_progress, self._group_only)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 182, in _notify
    self._status_message.edit_media(media=InputMediaPhoto(photo))
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2096, in edit_media
    return self.bot.edit_message_media(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2916, in edit_message_media
    return self._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Canceled by new editmessagemedia request
2022-04-04 16:41:37,836 - __main__ - ERROR - Job notifier_timer raisedCanceled by new editmessagemedia request
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 334, in _notify_by_time
    self._schedule_notification()
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 307, in _schedule_notification
    self._notify(mess, self._silent_progress, self._group_only)
  File "/home/pi/moonraker-telegram-bot/bot/notifications.py", line 182, in _notify
    self._status_message.edit_media(media=InputMediaPhoto(photo))
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/message.py", line 2096, in edit_media
    return self.bot.edit_message_media(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 2916, in edit_message_media
    return self._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Canceled by new editmessagemedia request

### If needed, paste the relevant bot journal contents here.

Apr 04 15:56:57 fluiddpi python[507]: FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/timelapse/nutinsert.gcode_2022-04-04_15-46/lapse.lock'
Apr 04 15:56:57 fluiddpi python[507]:     return self._accessor.open(self, flags, mode)
Apr 04 15:56:57 fluiddpi python[507]:   File "/usr/lib/python3.9/pathlib.py", line 1116, in _raw_open
Apr 04 15:56:57 fluiddpi python[507]:     fd = self._raw_open(flags, mode)
Apr 04 15:56:57 fluiddpi python[507]:   File "/usr/lib/python3.9/pathlib.py", line 1304, in touch
Apr 04 15:56:57 fluiddpi python[507]:     lock_file.touch()
Apr 04 15:56:57 fluiddpi python[507]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 423, in _create_timelapse
Apr 04 15:56:57 fluiddpi python[507]:     return self._create_timelapse(printing_filename, gcode_name, info_mess)
Apr 04 15:56:57 fluiddpi python[507]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 388, in create_timelapse
Apr 04 15:56:57 fluiddpi python[507]:     ) = self._camera.create_timelapse(lapse_filename, gcode_name, info_mess)
Apr 04 15:56:57 fluiddpi python[507]:   File "/home/pi/moonraker-telegram-bot/bot/timelapse.py", line 266, in _send_lapse
Apr 04 15:56:57 fluiddpi python[507]:     retval = job.func(*job.args, **job.kwargs)
Apr 04 15:56:57 fluiddpi python[507]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
Apr 04 15:56:57 fluiddpi python[507]: Traceback (most recent call last):
Apr 04 15:56:57 fluiddpi python[507]: 2022-04-04 15:56:57,628 - __main__ - ERROR - Job f7ec24eec26940b7898d44bc5fcc6b10 raised[Errno 2] No such file or directory: '/home/pi/timelapse/nutinsert.gcode_2022-04-04_15-46/lapse.lock'
Apr 04 15:56:55 fluiddpi python[507]: 2022-04-04 15:56:55,367 - apscheduler.executors.default - INFO - Job "Notifier._send_print_finish (trigger: date[2022-04-04 15:56:52 BST], next run at: 2022-04-04 15:56:52 BST)" executed successfully
Apr 04 15:56:54 fluiddpi python[507]: 2022-04-04 15:56:54,513 - apscheduler.executors.default - INFO - Job "Notifier._notify (trigger: date[2022-04-04 15:56:52 BST], next run at: 2022-04-04 15:56:52 BST)" executed successfully
Apr 04 15:56:53 fluiddpi python[507]: 2022-04-04 15:56:53,685 - apscheduler.executors.default - INFO - Job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2022-04-04 15:56:55 BST)" executed successfully
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,391 - apscheduler.executors.default - INFO - Running job "Notifier._send_print_finish (trigger: date[2022-04-04 15:56:52 BST], next run at: 2022-04-04 15:56:52 BST)" (scheduled at 2022-04-04 15:56:52.334097+01:00)
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,392 - apscheduler.scheduler - INFO - Removed job 895b139197b041ae85da32ef880c4420
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,367 - apscheduler.scheduler - INFO - Removed job f7ec24eec26940b7898d44bc5fcc6b10
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,365 - apscheduler.executors.default - INFO - Running job "Timelapse._send_lapse (trigger: date[2022-04-04 15:56:52 BST], next run at: 2022-04-04 15:56:52 BST)" (scheduled at 2022-04-04 15:56:52.316823+01:00)
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,341 - apscheduler.scheduler - INFO - Added job "Notifier._send_print_finish" to job store "default"
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,333 - apscheduler.scheduler - INFO - Added job "Timelapse._send_lapse" to job store "default"
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,327 - apscheduler.executors.default - INFO - Running job "Notifier._notify (trigger: date[2022-04-04 15:56:52 BST], next run at: 2022-04-04 15:56:52 BST)" (scheduled at 2022-04-04 15:56:52.313588+01:00)
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,326 - apscheduler.scheduler - INFO - Removed job a6252b22a0af42ebbe726ae580f7a84b
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,316 - apscheduler.scheduler - INFO - Removed job notifier_timer
Apr 04 15:56:52 fluiddpi python[507]: 2022-04-04 15:56:52,315 - apscheduler.scheduler - INFO - Added job "Notifier._notify" to job store "default"
Apr 04 15:56:50 fluiddpi python[507]: 2022-04-04 15:56:50,953 - apscheduler.executors.default - INFO - Running job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2022-04-04 15:56:55 BST)" (scheduled at 2022-04-04 15:56:50.950819+01:00)

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by nG64** [comment]
[timelapse]
basedir: /home/pi/timelapse
#	This sets the folder, where to save timelapse pictures and the resulting video. 
#	Default is '/tmp/timelapse', but you can set it to any catalog, which the bot 
#	has rights to write to. Might be useful for saving the sd cards life by writing to external storage.
copy_finished_timelapse_dir: /home/pi/timelapse/finished
#	This sets the folder, to which finished timelapses get copied to. 
#	The default behaviour is not to copy it anywhere. This might be useful, if you want to keep only the videos, 
#	but clean up the pictures, or if you want to upload the videos to some network location.
cleanup: true
#	Should the bot clean the catalog with pictures and video after the successful sending to the telegram chat.
#	Default is true. You might want to set it to false, if you intend on using the pictures later.
#height: 0
#	The bot can take timelapse pictures based on the z axis height (e.g. 0.2). The default is not to take pictures based on height.
#	Your layer height should be a multiple/equal to this number.
#time: 0
#	The bot can take timelapse pictures based on time intervals in seconds. 
#	The default is not to take pictures based on time intervals.
target_fps: 15  
#	This is the target fps of the created video. The larger this number, the "faster" the timelapse will be.
#	15 fps equals 15 images per second lapsing. The default is 15 fps.
#min_lapse_duration: 0
#	On short prints, or with limited lapse pictures available, the lapse often gets to short to meaningfully display
#	the printing progress. You can specify the desired minimum duration of the created timelapse 
#	(not including last_frame_duration). This means, that the fps will get reduced, if the lapse is shorter than this time.
#	The default is to omit this. 
#max_lapse_duration: 0
#	Similar to min_lapse_duration, if your lapse video gets too long to watch, you can specify a desired time, which
#	should not be exceeded. This means, that the fps will get increased, if the lapse is going to be longer than this time.
#	The default is to omit this. 
last_frame_duration: 5
#	This allows you to prevent the timelapse video from ending too abruptly. You can choose a duration for which 
#	to loop the last picture taken.
#	Default is 5 seconds. 
#after_lapse_gcode: /my_macro
#	You can run a macro or a gcode (e.g /gcode %your gcode here%) after the bot finishes building the timelapse.
#	This may be useful, if you intend shutting down the printer, if you want to automatically start another print,
#	or if you want to do something with the video after its ready. 
send_finished_lapse: true
#	If you want to build the lapse, but do not want to send it, set this to false. Default is true.
manual_mode: false
#	If True, only commands from gcode will manage timelapse.
#	Default is false.
#after_photo_gcode: 
#	You can enter any macro or gcode to be run after the "photo_and_gcode" command.
#	Default is not to run any gcode after the command.

**Comment by nG64** [comment]
[bot]
server: localhost
chat_id: 1307165099
bot_token: 5282066186:AAGPdZPkFti2A0JwSOah-lPhWguTI-BJMqQ
log_path: /home/pi/klipper_logs

[camera]
host: http://localhost:8080/?action=stream

[progress_notification]
percent: 5
height: 5
time: 5

[timelapse]
basedir: /home/pi/timelapse
copy_finished_timelapse_dir: /home/pi/timelapse/finished
cleanup: true
#height: 0height.
#time: 0
target_fps: 15  
#min_lapse_duration: 0
#max_lapse_duration: 0
last_frame_duration: 5
#after_lapse_gcode: /my_macro
send_finished_lapse: true
manual_mode: false
#after_photo_gcode:
