### ISSUE TITLE
[Bug]: Не снимает таймлапсы + не обновляет статус печати

### ISSUE THREAD

**Issue by kpp39** [nlef/moonraker-telegram-bot#180]
### What happened and in what context?

Загрузил клиппер, запустил печать. Статус обновляется только вручную, хотя в конфиге стоит и по таймеру, и по высоте, и по процентам. Также не происходит запись таймлапса. Лог прилагю

### If needed, paste the relevant bot log contents here.

Current Monraker telegram bot config
[bot]
server = localhost
bot_token = 
chat_id = 

[camera]
host = http://localhost:8080/?action=stream
fps = 25

[progress_notification]
percent = 10
height = 10
time = 600

[timelapse]
cleanup = true
height = 0.2
time = 5
target_fps = 15

2022-06-24 08:06:07,887 - klippy - WARNING - Empty thumbnail_path
2022-06-24 08:06:19,395 - __main__ - ERROR - 'dict' object has no attribute 'json'
2022-06-24 09:46:52,643 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,679 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,715 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,754 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,794 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,838 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,880 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,916 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:52,956 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,004 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,045 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,090 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,129 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,168 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,208 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,248 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,287 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,330 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,370 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,409 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,450 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,490 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,529 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,568 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,605 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,688 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,727 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,765 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,809 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,849 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,895 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:53,957 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:54,008 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:54,055 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:54,141 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:54,204 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:54,274 - camera - WARNING - Reading video frames queue exception 
2022-06-24 09:46:56,913 - camera - WARNING - Writing video frames queue exception <built-in method with_traceback of Full object at 0xa0f9a4a8>
2022-06-24 09:46:57,024 - camera - WARNING - Writing video frames queue exception <built-in method with_traceback of Full object at 0xa0f9a598>
2022-06-24 11:12:01,071 - __main__ - ERROR - Job 6340617d9d4542918902d924c5619fb1 raised[Errno 2] No such file or directory: '/tmp/timelapse/foot_V2_45mm_2h18m_0,20mm_225C_PETG_ENDER3PRO.gcode_2022-06-24_08-06/lapse.lock'
Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/timelapse.py", line 263, in _send_lapse
    ) = self._camera.create_timelapse(lapse_filename, gcode_name, info_mess)
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 420, in create_timelapse
    return self._create_timelapse(printing_filename, gcode_name, info_mess)
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 455, in _create_timelapse
    lock_file.touch()
  File "/usr/lib/python3.9/pathlib.py", line 1304, in touch
    fd = self._raw_open(flags, mode)
  File "/usr/lib/python3.9/pathlib.py", line 1116, in _raw_open
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/timelapse/foot_V2_45mm_2h18m_0,20mm_225C_PETG_ENDER3PRO.gcode_2022-06-24_08-06/lapse.lock'
2022-06-24 19:27:42,631 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 226, in get_updates
    updates = super().get_updates(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 3057, in get_updates
    self._post(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-06-24 19:29:03,236 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 363, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ConnectTimeoutError: (<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0xa31a8220>, 'Connect timed out. (connect timeout=5.0)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5316443677:AAELne9Ur181Uv8iv1mwwxFwu6IiumO4rgU/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0xa31a8220>, 'Connect timed out. (connect timeout=5.0)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 226, in get_updates
    updates = super().get_updates(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 3057, in get_updates
    self._post(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5316443677:AAELne9Ur181Uv8iv1mwwxFwu6IiumO4rgU/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0xa31a8220>, 'Connect timed out. (connect timeout=5.0)'))
2022-06-24 20:12:36,507 - __main__ - ERROR - 'dict' object has no attribute 'json'
2022-06-24 20:22:30,484 - __main__ - ERROR - 'gcode_position'
2022-06-24 20:22:31,488 - __main__ - ERROR - 'gcode_position'
2022-06-24 20:36:36,617 - __main__ - ERROR - Unknown state: cancelled

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
Дядь, ты помнишь что я просил? Приложи весь лог файлом

**Comment by kpp39** [comment]
> Дядь, ты помнишь что я просил? Приложи весь лог файлом
вот файл. я его весь и приложил, только не файлом)
[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/8980418/telegram.log)

**Comment by fcps3** [comment]
Someone solved this problem? Same here...
