### ISSUE TITLE
[Bug]: config can't use

### ISSUE THREAD

**Issue by ptsa** [nlef/moonraker-telegram-bot#187]
### What happened and in what context?

/home/orangepi/klipper_config/telegram.conf  Already set bot_token and chat_id
but can not use it
![QQ截图20220721122410](https://user-images.githubusercontent.com/4506307/180129537-3bb27aa1-1659-4f3c-8008-6f71c94d5b1f.png)
Also used
save and restart
sudo systemctl status moonraker-telegram-bot

### If needed, paste the relevant bot log contents here.

![QQ截图20220721122230](https://user-images.githubusercontent.com/4506307/180129426-e30ececd-a16a-4dee-a01a-1c01d88585a9.png)

### If needed, paste the relevant bot journal contents here.

Current Monraker telegram bot config
[bot]
server = localhost
bot_token = 
chat_id = 

[camera]
host = http://localhost:8080/?action=stream

[progress_notification]
percent = 5
height = 5
time = 5

[timelapse]
cleanup = true
height = 0.2
time = 5
target_fps = 30

2022-07-21 12:22:10,234 - __main__ - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/orangepi/moonraker-telegram-bot/bot/main.py", line 1437, in <module>
    bot_updater = start_bot(configWrap.bot.token, configWrap.bot.socks_proxy)
  File "/home/orangepi/moonraker-telegram-bot/bot/main.py", line 1027, in start_bot
    updater.start_polling()
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 372, in id
    return self.bot.id
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 366, in bot
    self._bot = self.get_me()
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 453, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/orangepi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Stack (most recent call last):
  File "/home/orangepi/moonraker-telegram-bot/bot/main.py", line 64, in handle_exception
    logger.error(

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by aka13-404** [comment]
You propably have connectivity issues, did you get this sorted?

**Comment by fcps3** [comment]
Someone solved this problem? Same here...
