### ISSUE TITLE
[Bug]: Timelapse compilation error

### ISSUE THREAD

**Issue by DrDaveone** [nlef/moonraker-telegram-bot#212]
### What happened and in what context?

x86: Debian 11.5 kenel 5.10.0-18-amd64
tgbot: b2a9ad3e27fbe90a49339a98246ba8cbfe3e0f3d: v1.4.5.1, py3.9

issue: не делает таймлапсы.
лог: после конфига 00:24 ошибка после запуска, 00:57 сборка таймлапса

### If needed, paste the relevant bot journal contents here.

*******************************************************************
Current Moonraker telegram bot config
[bot]
server = localhost

[camera]
host = http://localhost:8080/?action=stream
flip_vertically = false
flip_horizontally = false
video_duration = 15
fourcc = mp4v
picture_quality = low
threads = 1
fps = 30
video_buffer_size = 2

[progress_notification]
percent = 10
height = 5

[timelapse]
cleanup = true
target_fps = 15
manual_mode = false
min_lapse_duration = 10
max_lapse_duration = 20
last_frame_duration = 2

[telegram_ui]
require_confirmation_macro = false
include_macros_in_command_list = true
progress_update_message = false
silent_progress = true
silent_status = true
hidden_macros = TIMELAPSE_STOP, TIMELAPSE_CREATE, TIMELAPSE_PHOTO, TIMELAPSE_START, LIFT_ME_UP, M300, M500

[status_message_content]
sensors = SKR Mcu, Host Cpu Temp
heaters = extruder, heater_bed

*******************************************************************
2022-10-24 00:24:29,756 - __main__ - ERROR - 

2022-10-24 00:24:36,822 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 630, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/main.py", line 147, in status
    notifier.update_status()
  File "/home/klipper/moonraker-telegram-bot/bot/notifications.py", line 442, in update_status
    self._schedule_notification()
  File "/home/klipper/moonraker-telegram-bot/bot/notifications.py", line 334, in _schedule_notification
    self._notify(mess, self._silent_progress, self._group_only)
  File "/home/klipper/moonraker-telegram-bot/bot/notifications.py", line 174, in _notify
    with self._cam_wrap.take_photo() as photo:
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 294, in take_photo
    img.save(bio, "JPEG", quality=80, subsampling=0)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/Image.py", line 2320, in save
    save_handler(self, fp, filename)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 632, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode P as JPEG
2022-10-24 00:26:06,640 - __main__ - ERROR - Job fdcb32ed4aa345bcb1389cec9f3cb35d raisedcannot write mode P as JPEG
Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 630, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/notifications.py", line 174, in _notify
    with self._cam_wrap.take_photo() as photo:
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 294, in take_photo
    img.save(bio, "JPEG", quality=80, subsampling=0)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/Image.py", line 2320, in save
    save_handler(self, fp, filename)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 632, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode P as JPEG
2022-10-24 00:27:44,298 - __main__ - ERROR - Job 0f291f590dfb4567831e82fb8a1a240f raisedcannot write mode P as JPEG
Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 630, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/notifications.py", line 174, in _notify
    with self._cam_wrap.take_photo() as photo:
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 42, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 294, in take_photo
    img.save(bio, "JPEG", quality=80, subsampling=0)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/Image.py", line 2320, in save
    save_handler(self, fp, filename)
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 632, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode P as JPEG
2022-10-24 00:57:05,902 - __main__ - ERROR - Job 74a22a11f5ff4df6bcbe5ba1298e54dc raised[Errno 2] No such file or directory: '/home/klipper/moonraker-telegram-bot-timelapse/Mutter.gcode_2022-10-23_23-50/lapse.lock'
Traceback (most recent call last):
  File "/home/klipper/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/klipper/moonraker-telegram-bot/bot/timelapse.py", line 263, in _send_lapse
    ) = self._camera.create_timelapse(lapse_filename, gcode_name, info_mess)
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 420, in create_timelapse
    return self._create_timelapse(printing_filename, gcode_name, info_mess)
  File "/home/klipper/moonraker-telegram-bot/bot/camera.py", line 455, in _create_timelapse
    lock_file.touch()
  File "/usr/lib/python3.9/pathlib.py", line 1304, in touch
    fd = self._raw_open(flags, mode)
  File "/usr/lib/python3.9/pathlib.py", line 1116, in _raw_open
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/klipper/moonraker-telegram-bot-timelapse/Mutter.gcode_2022-10-23_23-50/lapse.lock'

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by nlef** [comment]
@DrDaveone pls, check  3e149f9
