### ISSUE TITLE
no preview and no timelapse 

### ISSUE THREAD

**Issue by KonradJuenger** [nlef/moonraker-telegram-bot#272]
Hi,

unfortunately the preview and timelapse is not working for me. I removed and reinstalled the bot via kiauh but no luck. 

[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/11463355/telegram.log)

Everything else like /video or /status does work

Thanks!

sudo journalctl -r -u moonraker-telegram-bot: 
`-- Journal begins at Tue 2023-02-21 05:08:04 CET, ends at Fri 2023-05-12 12:42:12 CEST. --
May 12 12:37:04 machin python[56616]: FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/moonraker-telegram-bot-timelapse/slicer/ghSlicer_117.gcode_1970-01-01_01-00/lapse.lock'
May 12 12:37:04 machin python[56616]:     return self._accessor.open(self, flags, mode)
May 12 12:37:04 machin python[56616]:   File "/usr/lib/python3.9/pathlib.py", line 1116, in _raw_open
May 12 12:37:04 machin python[56616]:     fd = self._raw_open(flags, mode)
May 12 12:37:04 machin python[56616]:   File "/usr/lib/python3.9/pathlib.py", line 1304, in touch
May 12 12:37:04 machin python[56616]:     lock_file.touch()
May 12 12:37:04 machin python[56616]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 457, in _create_timelapse
May 12 12:37:04 machin python[56616]:     return self._create_timelapse(printing_filename, gcode_name, info_mess)
May 12 12:37:04 machin python[56616]:   File "/home/pi/moonraker-telegram-bot/bot/camera.py", line 422, in create_timelapse
May 12 12:37:04 machin python[56616]:     ) = self._camera.create_timelapse(lapse_filename, gcode_name, info_mess)
May 12 12:37:04 machin python[56616]:   File "/home/pi/moonraker-telegram-bot/bot/timelapse.py", line 263, in _send_lapse
May 12 12:37:04 machin python[56616]:     retval = job.func(*job.args, **job.kwargs)
May 12 12:37:04 machin python[56616]:   File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
May 12 12:37:04 machin python[56616]: Traceback (most recent call last):
May 12 12:37:04 machin python[56616]: 2023-05-12 12:37:04,846 - __main__ - ERROR - Job 92564d79ec8049d39d22bd62397fb43c raised[Errno 2] No such file or directory: '/home/pi/moonraker-telegram-bot-timelapse/slicer/ghSlicer_117.gcode_1970-01-01_01-00/lapse.lock'
May 12 12:37:02 machin python[56616]: 2023-05-12 12:37:02,031 - apscheduler.executors.default - INFO - Job "Notifier._send_print_finish (trigger: date[2023-05-12 12:36:59 CEST], next run at: 2023-05-12 12:36:59 CEST)" executed successfully
May 12 12:36:59 machin python[56616]: 2023-05-12 12:36:59,620 - apscheduler.executors.default - INFO - Running job "Notifier._send_print_finish (trigger: date[2023-05-12 12:36:59 CEST], next run at: 2023-05-12 12:36:59 CEST)" (scheduled at 2023-05-12 12:36:59.611036+02:00)
May 12 12:36:59 machin python[56616]: 2023-05-12 12:36:59,618 - apscheduler.scheduler - INFO - Removed job 93b210e8781142f2975108d9ea821ef3
May 12 12:36:59 machin python[56616]: 2023-05-12 12:36:59,614 - apscheduler.executors.default - INFO - Running job "Timelapse._send_lapse (trigger: date[2023-05-12 12:36:59 CEST], next run at: 2023-05-12 12:36:59 CEST)" (scheduled at 2023-05-12 12:36:59.609219+02:00)
May 12 12:36:59 machin python[56616]: 2023-05-12 12:36:59,614 - apscheduler.scheduler - INFO - Added job "Notifier._send_print_finish" to job store "default"
May 12 12:36:59 machin python[56616]: 2023-05-12 12:36:59,612 - apscheduler.scheduler - INFO - Removed job 92564d79ec8049d39d22bd62397fb43c
May 12 12:36:59 machin python[56616]: 2023-05-12 12:36:59,610 - apscheduler.scheduler - INFO - Added job "Timelapse._send_lapse" to job store "default"
May 12 12:36:59 machin python[56616]: 2023-05-12 12:36:59,608 - apscheduler.scheduler - INFO - Removed job notifier_timer
May 12 12:36:57 machin python[56616]: 2023-05-12 12:36:57,053 - apscheduler.executors.default - INFO - Job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2023-05-12 12:37:02 CEST)" executed successfully
May 12 12:36:57 machin python[56616]: 2023-05-12 12:36:57,052 - apscheduler.executors.default - INFO - Running job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2023-05-12 12:37:02 CEST)" (scheduled at 2023-05-12 12:36:57.050222+02:00)
May 12 12:36:56 machin python[56616]: 2023-05-12 12:36:56,617 - apscheduler.scheduler - INFO - Removed job timelapse_timer
May 12 12:36:55 machin python[56616]: 2023-05-12 12:36:55,054 - apscheduler.executors.default - INFO - Job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:57 CEST)" executed successfully
May 12 12:36:55 machin python[56616]: 2023-05-12 12:36:55,053 - apscheduler.executors.default - INFO - Running job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:57 CEST)" (scheduled at 2023-05-12 12:36:55.051381+02:00)
May 12 12:36:53 machin python[56616]: 2023-05-12 12:36:53,054 - apscheduler.executors.default - INFO - Job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:55 CEST)" executed successfully
May 12 12:36:53 machin python[56616]: 2023-05-12 12:36:53,053 - apscheduler.executors.default - INFO - Running job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:55 CEST)" (scheduled at 2023-05-12 12:36:53.051381+02:00)
May 12 12:36:52 machin python[56616]: 2023-05-12 12:36:52,053 - apscheduler.executors.default - INFO - Job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2023-05-12 12:36:57 CEST)" executed successfully
May 12 12:36:52 machin python[56616]: 2023-05-12 12:36:52,052 - apscheduler.executors.default - INFO - Running job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2023-05-12 12:36:57 CEST)" (scheduled at 2023-05-12 12:36:52.050222+02:00)
May 12 12:36:51 machin python[56616]: 2023-05-12 12:36:51,054 - apscheduler.executors.default - INFO - Job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:53 CEST)" executed successfully
May 12 12:36:51 machin python[56616]: 2023-05-12 12:36:51,053 - apscheduler.executors.default - INFO - Running job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:53 CEST)" (scheduled at 2023-05-12 12:36:51.051381+02:00)
May 12 12:36:49 machin python[56616]: 2023-05-12 12:36:49,054 - apscheduler.executors.default - INFO - Job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:51 CEST)" executed successfully
May 12 12:36:49 machin python[56616]: 2023-05-12 12:36:49,053 - apscheduler.executors.default - INFO - Running job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:51 CEST)" (scheduled at 2023-05-12 12:36:49.051381+02:00)
May 12 12:36:47 machin python[56616]: 2023-05-12 12:36:47,055 - apscheduler.executors.default - INFO - Job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:49 CEST)" executed successfully
May 12 12:36:47 machin python[56616]: 2023-05-12 12:36:47,054 - apscheduler.executors.default - INFO - Job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2023-05-12 12:36:52 CEST)" executed successfully
May 12 12:36:47 machin python[56616]: 2023-05-12 12:36:47,053 - apscheduler.executors.default - INFO - Running job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:49 CEST)" (scheduled at 2023-05-12 12:36:47.051381+02:00)
May 12 12:36:47 machin python[56616]: 2023-05-12 12:36:47,053 - apscheduler.executors.default - INFO - Running job "Notifier._notify_by_time (trigger: interval[0:00:05], next run at: 2023-05-12 12:36:52 CEST)" (scheduled at 2023-05-12 12:36:47.050222+02:00)
May 12 12:36:45 machin python[56616]: 2023-05-12 12:36:45,054 - apscheduler.executors.default - INFO - Job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:47 CEST)" executed successfully
May 12 12:36:45 machin python[56616]: 2023-05-12 12:36:45,054 - apscheduler.executors.default - INFO - Running job "Timelapse.take_lapse_photo (trigger: interval[0:00:02], next run at: 2023-05-12 12:36:47 CEST)" (scheduled at 2023-05-12 12:36:45.051381+02:00)
lines 1-43`

**Comment by KonradJuenger** [comment]
I reinstalled everything on a clean "pi os lite" but still no luck:

![grafik](https://github.com/nlef/moonraker-telegram-bot/assets/76114767/d4a2e520-39a3-4c16-888f-ebcc78a2d4ee)

[telegram_2.log](https://github.com/nlef/moonraker-telegram-bot/files/11465146/telegram_2.log)
[journalctl.log](https://github.com/nlef/moonraker-telegram-bot/files/11465200/journalctl.log)

**Comment by KonradJuenger** [comment]
seems to be a "only me problem" and related to the custom gcode I am using. I switched to https://github.com/mainsail-crew/moonraker-timelapse, which works for me. It would be cool if the bot could use this timelapse module, since it is really well integrated in Mainsail
