### ISSUE TITLE
[Bug]: Standard config with fresh Pi+Kiauh doesn't work

### ISSUE THREAD

**Issue by MatteAce** [nlef/moonraker-telegram-bot#288]
### What happened and in what context?

I've installed a fresh Pi 3B (with USB startup disk) with the Raspberry Installer, Lite 32-bit.
Installed Kiauh, installed klipper, moonraker, mainsail. Updated everything.

Installed Telegram Bot, got a key from BotFather, included it in the config.

The bot won't answer, log says uncaught exception. I have no idea why. The Pi is definitely connected to the internet since I can update everything. Tried to reinstall it three times, still through Kiauh, still broken. 

I don't know if it's relevant, but Mainsail through the Moonraker Update Manager UI has the moonraker-telegram-bot v1.5-0-gb9b47003 green "up-to-date" button on the right saying instead "UNKNOWN".

![CleanShot 2023-09-30 at 17 28 16](https://github.com/nlef/moonraker-telegram-bot/assets/17239209/f2629501-11c8-4e2e-9ee9-a4c6e708e2d7)

I've also tried adding the user/password section in the bot config and adding my system's username (not root) and pass but nothing changed, I only got a slightly longer and more angry log.

Please help.

### If needed, paste the relevant bot log contents here.

*******************************************************************
Current Moonraker telegram bot config
[bot]
server = localhost

[progress_notification]
percent = 5
height = 5
time = 5

[timelapse]
cleanup = true
height = 0.2
time = 5
target_fps = 30

*******************************************************************
2023-09-30 17:13:22,590 - __main__ - ERROR - 

2023-09-30 17:13:22,922 - __main__ - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 1106, in <module>
    bot_updater = start_bot(configWrap.secrets.token, configWrap.bot_config.socks_proxy)
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 1047, in start_bot
    updater.start_polling()
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 377, in id
    return self.bot.id
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 371, in bot
    self._bot = self.get_me()
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 458, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized
Stack (most recent call last):
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 64, in handle_exception
    logger.error(

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by MatteAce** [comment]
Just tried commenting the whole [authorization] section in moonraker.conf and nothing changed

**Comment by MatteAce** [comment]
AGH! an unwanted character got mixed up in the auth code got from BotFather... it was as easy as copypasting the auth code again. Fixed, sorry!
