### ISSUE TITLE
[Bug]: power toggle won't work

### ISSUE THREAD

**Issue by cruzer619** [nlef/moonraker-telegram-bot#339]
### What happened and in what context?

After upgrading to latest version of telegram-bot when printer is off but pi is still on.  Power toggle no longer works.  I've tried to uninstall and reinstall. and same result.  Also when first starting the printer.  And assuming the service starts.  Printer online status notification sends every 30 secs.  After I stop and restart service it will stop sometimes.

### If needed, paste the relevant bot log contents here.

*******************************************************************
Current Moonraker telegram bot config
[bot]
server = localhost
power_device = Ender5
light_device = LED1

[progress_notification]
percent = 10

*******************************************************************
2024-12-09 01:38:35,438 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:36,455 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:37,467 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:38:37,472 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:38,487 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:39,501 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:38:39,505 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:40,519 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:41,536 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:38:41,540 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:42,562 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:43,599 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:44,603 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:38:44,622 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/info'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:45,645 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:38:46,267 - klippy - ERROR - klippy.py:362 - Server error '503 Klippy Host not connected' for url 'http://localhost/printer/objects/list'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
2024-12-09 01:38:47,435 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
trunk
2024-12-09 01:48:15,435 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:48:17,435 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:48:19,437 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:48:21,437 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
2024-12-09 01:48:22,413 - __main__ - ERROR - main.py:986 - Exception while handling an update:
Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    raise exc
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_async/connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 122, in connect_tcp
    stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
    res = await self._client.request(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/_application.py", line 1319, in process_update
    await coroutine
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/_handlers/basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
  File "/home/pi/moonraker-telegram-bot/bot/main.py", line 447, in power
    await update.effective_message.get_bot().send_chat_action(chat_id=configWrap.secrets.chat_id, action=ChatAction.TYPING)
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 2520, in send_chat_action
    return await super().send_chat_action(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/_bot.py", line 3443, in send_chat_action
    return await self._post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/_bot.py", line 617, in _post
    return await self._do_post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 351, in _do_post
    return await super()._do_post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/_bot.py", line 646, in _do_post
    result = await request.post(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 202, in post
    result = await self._request_wrapper(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 334, in _request_wrapper
    code, payload = await self.do_request(
  File "/home/pi/moonraker-telegram-bot-env/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 310, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
2024-12-09 01:48:23,440 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}
trunk
2024-12-09 01:53:49,434 - websocket_helper - WARNING - websocket_helper.py:312 - Error received from websocket: {'code': 503, 'message': 'Klippy Host not connected'}

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by cruzer619** [comment]
ok was able to fix the printer online status repeating every 30 secs.  Referencing #326, I used kiauh alpha 6 to reinstall.  I manually installed via git.  So I'm good there, but "/power" function doesn't work unless I'm at my home computer to turn it on.
![Screenshot 2024-12-11 164029](https://github.com/user-attachments/assets/7f7845c2-7edf-4dc1-b6fe-12ea6afc6289) 
on 1.5.0 I was able to power on printer when it was in the off state.  Will try to uninstall latest version and manually install previous version, unless there is an easy way to roll back.

Thanks

RC

**Comment by cruzer619** [comment]
ok rolled back to 1.5.0 and now able to power on printer when its off.  so using RP 4 with relay to turn on/off printer mainboard via moonraker.

**Comment by nlef** [comment]
@cruzer619 
Most likely you are using power devices that control klipper output_pin. In the latest versions of moonraker, when the klipper is in shutdown/error state, switching such power devices is impossible.
The API for controlling power devices has not changed in moonraker, the logic for working with it has not changed in the bot.
For convenience, I added the output of an error message in the reply message when controlling power devices from the bot in [add8df3](https://github.com/nlef/moonraker-telegram-bot/commit/add8df380d32a946842da9e03319ef31ac5d18bf)
It would be cool if you could test and indicate the errors that occur when working with power devices for you.

**Comment by cruzer619** [comment]
![image](https://github.com/user-attachments/assets/c9dd8247-e4c2-443e-a1bd-3c1b164125c9)
@nlef yes I am using GPIO pins to toggle relay on/off.  ok just got home from out of state.  Will give this a try and send error test message.

**Comment by cruzer619** [comment]
[telegram.log](https://github.com/user-attachments/files/18289132/telegram.log)
Here is the latest telegram log.  And going to leave installation at v2.0.0 for now.

**Comment by nlef** [comment]
@cruzer619 
judging by the attached log file, you are using a bot from the master branch. Unfortunately, you won't be able to test the commit I specified above. Could you add `debug: true` to the section `bot` in the bot config file, restart the bot, switch the power device and attach a new bot log?

**Comment by cruzer619** [comment]
![image](https://github.com/user-attachments/assets/e887b96b-e19f-43eb-88f9-fdd22296aad4)
my bad.. I thought I grabbed development branch.. saw in notes you added "power device error"...  so from this screen.  I thought if I clicked on the green code button, and copied the url from there would git the develpment branch.  or is there another way of doing it?

**Comment by cruzer619** [comment]
[telegram.log](https://github.com/user-attachments/files/18289993/telegram.log)
Here is new log with bot => debug: true

update:  just noticing with debug being on.. the power on dialog is showing up sometimes.. but doesn't power on printer.
also think I found the right syntax for git and branch download..
`git clone --single-branch --branch <branchname> <remote-repo>`
but won't update via git unless you say so.

**Comment by nlef** [comment]
```
cd ~/moonraker-telegram-bot
git checkout development
```

also you could add `primary_branch: development` into moonraker config update_manager section for the bot. This will give the ability to update the bot from the dev branch from the web interface

**Comment by cruzer619** [comment]
ok thanks will update and try again... but will need some sleep..  will try again in about 5 hours..  thanks.

**Comment by cruzer619** [comment]
[telegram.log](https://github.com/user-attachments/files/18293054/telegram.log)
ok here is new log.  I updated to development branch.  turned off debug mode.  I did like 5 power toggles and after about 3 min "5 power on dialogs" showed up.  hit power on and printer turned on.  but when I pressed power toggle again. about 5 times.  no diaglog to turn off printer.  so its not just to power it on.  seems to be lack of some communication.  as I tried status as well.  and no dialog either with a pic.

**Comment by cruzer619** [comment]
FYI I've started to print my ERCF v2 parts.  Won't be able to test 'til the following day.

UPDATE: able to test whenever ready.

**Comment by nlef** [comment]
@cruzer619 
a logical bug with blocking in power devices was found and fixes 
please update to the latest version in the development branch and test

**Comment by cruzer619** [comment]
current version: moonraker-telegram-bot v2.0.0-11-g7887262e

good morning.. ( well for me )  will update now and test
UPDATE:
[telegram.log](https://github.com/user-attachments/files/18308072/telegram.log)
here is the log file..
I updated repo.. power seems to be working..  I had to send power switch 2 - 3 times before it took.  Then after was able to power on/off repeatedly 1 at a time.  Didn't take several times for it to acknowledge the switch.  But `/status` isn't working at all.  Not sure if wasn't working to begin with or just now with update.
Update 2:
[telegram2.log](https://github.com/user-attachments/files/18308185/telegram2.log)
ok I rebooted PI and did more testing..  after reboot, tried power switch nothing.. no matter how many times...  but as soon as I hit light switch and turned light on/off.  Then I was able to hit power switch and working as expected.  so uploaded 2nd log for this behavior.  also after reboot, normally I get a message while on v1.5 in telegram notification : "Bot online, no moonraker connection!  Connection Failed. Not Found Failing...".  In v2.0 not getting that notification on reboot. ( maybe you removed that on purpose.. I see you made updates to notifications )

**Comment by nlef** [comment]
judging by the logs, the bot cannot connect to the moonraker. I added processing and outputting connection errors to the moonraker in the status command respond.
The welcome message in version 2 appears a little later. The bot tries to connect to the moonraker for up to 1 minute and in case of a successful connection or expiration of the specified time, it sends a message about the connection or with the error text

**Comment by cruzer619** [comment]
roger will update repo and try again.. its jus strange light switch acknowledges right away every time...

**Comment by cruzer619** [comment]
current version: moonraker-telegram-bot v2.0.0-12-ge2656301

[telegram.log](https://github.com/user-attachments/files/18311726/telegram.log)
Here is the log and here is snap shot of my sequence.  Oh and after this power switch every time until next reboot.  then have to do light switch hack first for it to retain.  And status switch never works but when I print it does send a status but only sent on the first 10% after that no more status notifications. 

Update2:
[telegram3.log](https://github.com/user-attachments/files/18311829/telegram3.log)
ok playing around more...  if I do 2 power switch command in a row.. works without the need of using light switch hack.  but always requires 2.

Update3:
Ok I have a feeling why status isn't working as it can't get camera pic.  was playing some more and can't get it send video either.  I'm just guessing here.  assuming if I set camera to nothing should work.. going to test.  
*** yup that was it.. status works with no camera set.  so for some reason doesn't like my ip camera.  which is a pi zero w running motioneye os.  if I set to localhost camera which is my nozzle cam.  status works and so does video.  So seems for me.. there is a communication issue with v2. compared to v1.5  Oh and I already tried changing from localhost to PI's IP and that made it worse.

Update4:
<strike>ok got camera working.  Just added more details instead of just camera host.  </strike>     after reboot didnt work, only localhost works.
[telegram.log](https://github.com/user-attachments/files/18312058/telegram.log)
so after changing camera to localhost.  all switches are working fine after a reboot.  sometimes have to double switch.. but all controls are working.  So the issue was camera set to an IP.

![image](https://github.com/user-attachments/assets/dd88b982-3a3d-4349-9bc6-cd9d28ed33aa)

**Comment by cruzer619** [comment]
current version: moonraker-telegram-bot v2.0.0-14-g294dd48a

ok updated to latest dev repo and your 15 sec max timeout working.  I only have to do a power switch one time.  Will test other switches but have a feeling its all fixed except for status and IP camera .

Update:
doing several switches all only 1 time.  never had to do double switching like before.

**Comment by nlef** [comment]
In version 2 camera settings have been changed and parameter `type` was added with the default value `mjpeg`.
If your remote camera is not streaming mjpeg, you have to set `type`:`opencv` in camera settings.
Pls take a look at the release notes of version 2 and wiki

**Comment by cruzer619** [comment]
@nlef correct I was looking at that.  At first was working but after reboot it failed.. should show in last log.  I was using:

[camera]
host = http://192.168.1.110:8081/
type = ffmpeg
host_snapshot = http://192.168.1.110/picture/1/frame/

will try again.

Update:
OK I put back the same settings as above and is working after reboot this time.  going to assume the 15sec max timeout is doing its thing.  I'm a happy camper.

**Comment by cruzer619** [comment]
After more testing and reboots all is fixed with power toggle and status on dev branch.  closing ticket.

**Comment by cruzer619** [comment]
@nlef just wanted to report typo on /status when not connected to for webhooks.  Should say "Failed" but saying "Filed"

`**Filed** to get status: `Server error '503 Klippy Host not connected' for url 'http://localhost/printer/objects/query?webhooks&print_stats&display_status'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503``

found the error in klippy.py line 541 but its only in dev repo.. master doesn't have that typo, will try to submit pull request never done it before.  Looks like I can't create pull request.. oh well I tried :)

**Comment by nlef** [comment]
@cruzer619  Thank you very much for testing and help!
I fixed the typo in error message and changed schedulling logic for greeting message, so you should receive "Bot online" messages after bot starts.

**Comment by cruzer619** [comment]
@nlef sure its my pleasure to help out.. and after updating to latest dev repo.. welcome message shows up.. and quick testing all is working.  sweat!!!!!
